name: Got Africa-Inspired
slogan: Got inspired by Africa. <em>Sharing it!</em> 

markdown: redcarpet
highlighter: false
relative_permalinks: false

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - gems
  
google_analytics_id: UA-20582361-3
feedburner_id: GotAfricaInspired
showcased_video_id: LLwVZ-WvDYE
showcased_video_teaser: "Nnaemeka Ikegwuonu's story: Founding a radio station to help support and educate farmers."


