name: Got Africa-Inspired
slogan: Got inspired by Africa. <em>Sharing it!</em> 

markdown: redcarpet
highlighter: false
relative_permalinks: false

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - gems
  
google_analytics_id: UA-20582361-3
feedburner_id: GotAfricaInspired
showcased_video_id: csmxsoCkIqM
showcased_video_teaser: "Bibi Tanga & The Selenites in an impressive video clip for the song <em>Be Africa</em>."


