name: Got Africa-Inspired
slogan: Collections of awesome African stories and creations 
markdown: redcarpet
pygments: false
relative_permalinks: false
google_analytics_id: UA-20582361-3
feedburner_id: GotAfricaInspired
showcased_video_id: 1vmxRUN12c0
showcased_video_teaser: "The Afro-Jazz / Fusion drummer from Côte d'Ivoire, Paco Sery, performing and living on <em>Chabada danse</em>."

