name: Got Africa-Inspired
slogan: Collections of awesome African stories and creations 

markdown: redcarpet
highlighter: false
relative_permalinks: false

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - gems
  
google_analytics_id: UA-20582361-3
feedburner_id: GotAfricaInspired
showcased_video_id: Qxcm-rfDdSQ#t=12
showcased_video_teaser: "<em>Accra [dot] Alt</em> presents <em>Chale Wote</em> Street Art Festival."


